# Generated by Django 5.1.4 on 2024-12-21 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("dynasty", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                (
                    "poem_type",
                    models.CharField(
                        choices=[("五言诗", "五言诗"), ("七言诗", "七言诗")],
                        default="五言诗",
                        max_length=10,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("low", "Low"), ("mid", "Mid"), ("high", "High")],
                        default="mid",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_part", models.CharField(max_length=100)),
                ("second_part", models.CharField(max_length=100)),
                (
                    "poetry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentences",
                        to="poetry_app.poetry",
                    ),
                ),
            ],
        ),
    ]
