spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  #这一行指定了数据源配置的相关项，用于连接和管理数据库。
  datasource:
    #这一行配置了数据库的连接 URL，指定了数据库的地址、端口、数据库名称等信息
    url: jdbc:mysql://localhost:3306/hci?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: cph

    #这一行指定了 JPA（Java Persistence API）的相关配置。
    password: 123456
  jpa:
    #这一行指定了 Hibernate 的相关配置。Hibernate 是一个流行的 Java ORM（对象关系映射）框架
    hibernate:
      #这一行配置了 Hibernate 的 ddl-auto 属性，用于在应用程序启动时自动更新数据库的表结构。"update" 表示 Hibernate 会根据实体类的定义自动创建或更新数据库的表结构。
      ddl-auto: update



server:
  port: 8080
